require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION = "2"

shackHamlPath = File.expand_path("Shack.yaml")
afterScriptPath = File.expand_path("scripts/after.sh")
aliasesPath = File.expand_path("scripts/aliases")

require_relative 'shack.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if File.exists? aliasesPath then
    config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
  end

  Shack.configure(config, YAML::load(File.read(shackHamlPath)))

  if File.exists? afterScriptPath then
    config.vm.provision "shell", path: afterScriptPath
  end
end
